version: '3'
services:
  frontend:
    stdin_open: true
    tty: true
    container_name: fe-react-typescript
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
